configuration: Release

version: '0.4.{build}'

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"	
  assembly_informational_version: "{version}"

install:
- ps: >-
    (new-object net.webclient).DownloadFile('https://ci.appveyor.com/api/buildjobs/tojql4tt0xu7orxa/artifacts/MikTex.2.9.2.9711.msi', 'C:\\MikTex.2.9.2.9711.msi')

    msiexec /i C:\\MikTex.2.9.2.9711.msi /quiet /qn /norestart /log install.log

    cat install.log

cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

nuget:
  account_feed: true

after_test:
  cmd: dev\TestApp\bin\Release\TestApp.exe these are arguments

before_build:
  - nuget restore

