configuration: Release

version: '0.4.{build}'

platform:
  - x86

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"	
  assembly_informational_version: "{version}"

environment:
  COVERALLS_REPO_TOKEN:
    secure: v/xn8Q6QR9FsktGqr8V3oYpO88W2BXOIb/amH2c660IMGCZjw5qKJHCxHedX30vL

#install:
#- ps: >-
#    (new-object net.webclient).DownloadFile('https://ci.appveyor.com/api/buildjobs/tojql4tt0xu7orxa/artifacts/MikTex.2.9.2.9711.msi', 'C:\\MikTex.2.9.2.9711.msi')
#
#    Start-Process C:\Windows\System32\msiexec.exe -ArgumentList /i, C:\MikTex.2.9.2.9711.msi, /quiet, /qn, /norestart, /log, C:\install.log -Wait
#
#    cat C:\install.log
#
#    ls c:\

notifications:
  - provider: Slack
    incoming_webhook:
      secure: Cj9sJjs1yQRd5bR3A8XzwPhGEZ5fm9BXfEGxcSeekCiA/eeM2qa6d2eYr6gg95SaVsOKFkUnbCc9uuXTTH6bSOUcUXpcpJL0+pWXYKwpLjo=

before_build:
  - nuget restore
  - ruby scripts/postclean-ci.rb

build:
  project: ConsoleApp.sln 

after_build:
  - rake "create_setup[%APPVEYOR_BUILD_VERSION%, %CONFIGURATION%]"
  - 7z a setup.zip %APPVEYOR_BUILD_FOLDER%\setup\**\*.msi

cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

nuget:
  account_feed: true

test_script: 
  - ps: ./packages/**/tools/report-coverage.ps1 -categoryFilter cat!=ReportingTest

after_test:
  - ps: ./*/TestApp/bin/*/TestApp.exe these are arguments

on_finish: 
  - ps: Get-ChildItem ./**/setup.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

artifacts:
  - path: setup.zip
    name: setup